apiVersion: apps/v1
kind: Deployment
metadata:
  name: lv-a3
  namespace: default
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: lv-a3
  template:
    metadata:
      labels:
        app: lv-a3
        version: v1
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
      containers:
      - name: php
        image: docker.io/library/kind-apps--lv:latest
        imagePullPolicy: Never
        envFrom:
        - configMapRef:
            name: lv-base
        env:
        - name: APP_NAME
          value: "Laravel A3"
        resources:
          requests:
            memory: "256Mi"
            cpu: "1"
          limits:
            memory: "256Mi"
            cpu: "1"
        ports:
        - containerPort: 8080
